name: CI Build and Test

# Trigger the workflow on push and pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the job that will run
jobs:
  build:
    # The job will run on Ubuntu
    runs-on: ubuntu-latest

    # Define the steps of the job
    steps:
      # Step 1: Check out the repository
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Step 2: Set up CMake (used for building the project)
      - name: Set up CMake
        uses: lukka/get-cmake@v3

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev cmake

      # Step 4: Build the project (client and server)
      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      # Step 5: Run tests (client, server, and shared tests)
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      # Step 6: Upload test results (optional)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/Testing

  # Second job: Docker image build for deployment (optional)
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images for server and client
        run: |
          docker-compose -f docker-compose.yml build

      - name: Push Docker images (optional)
        run: |
          docker-compose -f docker-compose.yml push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
